@Echo off
title MCrasher debug console v.1.0
echo loading......
echo loading......
echo loading......
echo loading......
echo loading......
echo loading......
echo loading......
cls
start C:\Users\tululum\AppData\Roaming\.minecraft\TLauncher.exe
echo Crash Tlauncher.exe?
pause
taskkill -f -im javaw.exe
pause


